### ISSUE TITLE
npm run build 报错 

### ISSUE THREAD

**Issue by richwxd** [pcloth/ve-calendar#1]
ERROR in static/js/vendor.7fac05115e45003ae53f.js from UglifyJs
Unexpected token name «i», expected punc «;» [./node_modules/ve-calendar/src/lib/js/calendar.js:539,0][static/js/vendor.7fac05115e45003ae53f.js:155736,17]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-admin@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-admin@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pcloth** [comment]
什么版本，推荐更新到0.3.2最新版。

**Comment by richwxd** [comment]
好像是ES6的问题，排除后，IE9,IE10无法打开
